name: :love_letter: Enhancement
description: File a bug/issue
title: "[ENHANCEMENT] <title>"
labels: [Enhancement, Needs Triage]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing using the current interaction principles.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen or the enhancement you wish to see.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this principle...
      3. Behave in this way '...'
      4. Experience this issue...
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
